name: cpp-linter
permissions: read-all

on:
  pull_request:
    branches:
      - master
    paths-ignore: "tests/**"

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shenxianpeng/cpp-linter-action@master
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          tidy-checks: >
            bugprone-*,
            performance-*,
            readability-*,
            portability-*,
            modernize-*,
            clang-analyzer-*,
            cppcoreguidelines-*,
            -modernize-use-trailing-return-type

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
